version: "3.9"
   
services:
  graph_notebook:
    image: aws-graph-notebook
    volumes:
      - ${PWD}/notebooks:/notebooks
      - ${PWD}/graph_notebook_config.json:/root/graph_notebook_config.json 
    ports:
      - "18888:8888"
    # environment:
    #   - POSTGRES_DB=postgres
    command: jupyter notebook /notebooks --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.password='sha1:5700fc3cc4af:9cd2df7544f3a0821b478024b2259950d66624ca'